import AppSidebarContentPanel from "./AppSidebarContentPanel";
import AppSidebarFrame from "./AppSidebarFrame";
import SidebarAgentsPanel from "./SidebarAgentsPanel";

export default function AppSidebarPane({
  isMobileLayout,
  isSidebarOpen,
  isDesktopSidebarCollapsed,
  sidebarStyle,
  isResizingSidebar,
  onToggleSidebarOpen,
  onToggleSidebarCollapsed,
  onStartSidebarResize,
  turnNotificationEnabled,
  setTurnNotificationEnabled,
  persistTurnNotificationEnabled,
  onToggleTheme,
  theme,
  sessionSummary,
  toggleAgent,
  agentConfigLoading,
  agentConfigSaving,
  openAgentSettings,
  activeSubagents,
  agentConfigError,
  activeAgentDef,
  activeAgentConfig,
  settingsBusy,
  updateAgentDraft,
  activeAgentSettings,
  guardianRuleSummary,
  floatingAgentSettings,
  toggleFloatingAgentSettings,
  loadAgentConfig,
  setAgentConfigError,
  saveAgentSettings,
  interactionBusy,
  projectItems,
  selectProject,
  projectTabs,
  activeProjectTabId,
  projectTabStatusById,
  onSelectProjectTab,
  onCloseProjectTab,
  threadItems,
  threadTabsByProjectTabId,
  activeThread,
  onSelectThread,
  onCloseThread,
  onAddThread,
  disableAddThread,
}) {
  return (
    <AppSidebarFrame
      isMobileLayout={isMobileLayout}
      isSidebarOpen={isSidebarOpen}
      isDesktopSidebarCollapsed={isDesktopSidebarCollapsed}
      sidebarStyle={sidebarStyle}
      isResizingSidebar={isResizingSidebar}
      onToggleSidebarOpen={onToggleSidebarOpen}
      onToggleSidebarCollapsed={onToggleSidebarCollapsed}
      onStartSidebarResize={onStartSidebarResize}
      settingsContent={
        <SidebarAgentsPanel
          sessionSummary={sessionSummary}
          toggleAgent={toggleAgent}
          agentConfigLoading={agentConfigLoading}
          agentConfigSaving={agentConfigSaving}
          openAgentSettings={openAgentSettings}
          activeSubagents={activeSubagents}
          agentConfigError={agentConfigError}
          activeAgentDef={activeAgentDef}
          activeAgentConfig={activeAgentConfig}
          settingsBusy={settingsBusy}
          updateAgentDraft={updateAgentDraft}
          activeAgentSettings={activeAgentSettings}
          guardianRuleSummary={guardianRuleSummary}
          floatingAgentSettings={floatingAgentSettings}
          toggleFloatingAgentSettings={toggleFloatingAgentSettings}
          loadAgentConfig={loadAgentConfig}
          setAgentConfigError={setAgentConfigError}
          saveAgentSettings={saveAgentSettings}
        />
      }
    >
      <AppSidebarContentPanel
        turnNotificationEnabled={turnNotificationEnabled}
        setTurnNotificationEnabled={setTurnNotificationEnabled}
        persistTurnNotificationEnabled={persistTurnNotificationEnabled}
        onToggleTheme={onToggleTheme}
        theme={theme}
        onToggleSidebarOpen={onToggleSidebarOpen}
        onToggleSidebarCollapsed={onToggleSidebarCollapsed}
        isMobileLayout={isMobileLayout}
        interactionBusy={interactionBusy}
        projectItems={projectItems}
        selectProject={selectProject}
        projectTabs={projectTabs}
        activeProjectTabId={activeProjectTabId}
        projectTabStatusById={projectTabStatusById}
        onSelectProjectTab={onSelectProjectTab}
        onCloseProjectTab={onCloseProjectTab}
        threadItems={threadItems}
        threadTabsByProjectTabId={threadTabsByProjectTabId}
        activeThread={activeThread}
        onSelectThread={onSelectThread}
        onCloseThread={onCloseThread}
        onAddThread={onAddThread}
        disableAddThread={disableAddThread}
      />
    </AppSidebarFrame>
  );
}
