import AppSidebarContentPanel from "./AppSidebarContentPanel";
import AppSidebarFrame from "./AppSidebarFrame";

export default function AppSidebarPane({
  isMobileLayout,
  isSidebarOpen,
  isDesktopSidebarCollapsed,
  sidebarStyle,
  isResizingSidebar,
  onToggleSidebarOpen,
  onToggleSidebarCollapsed,
  onStartSidebarResize,
  SidebarChevronIcon,
  turnNotificationEnabled,
  setTurnNotificationEnabled,
  persistTurnNotificationEnabled,
  onToggleTheme,
  theme,
  sessionSummary,
  toggleAgent,
  agentConfigLoading,
  agentConfigSaving,
  openAgentSettings,
  activeSubagents,
  agentConfigError,
  activeAgentDef,
  activeAgentConfig,
  settingsBusy,
  updateAgentDraft,
  activeAgentSettings,
  guardianRuleSummary,
  floatingAgentSettings,
  toggleFloatingAgentSettings,
  loadAgentConfig,
  setAgentConfigError,
  saveAgentSettings,
  interactionBusy,
  projectItems,
  activeProjectKey,
  selectProject,
  threadItems,
  activeThread,
  viewThread,
}) {
  return (
    <AppSidebarFrame
      isMobileLayout={isMobileLayout}
      isSidebarOpen={isSidebarOpen}
      isDesktopSidebarCollapsed={isDesktopSidebarCollapsed}
      sidebarStyle={sidebarStyle}
      isResizingSidebar={isResizingSidebar}
      onToggleSidebarOpen={onToggleSidebarOpen}
      onToggleSidebarCollapsed={onToggleSidebarCollapsed}
      onStartSidebarResize={onStartSidebarResize}
      SidebarChevronIcon={SidebarChevronIcon}
    >
      <AppSidebarContentPanel
        turnNotificationEnabled={turnNotificationEnabled}
        setTurnNotificationEnabled={setTurnNotificationEnabled}
        persistTurnNotificationEnabled={persistTurnNotificationEnabled}
        onToggleTheme={onToggleTheme}
        theme={theme}
        sessionSummary={sessionSummary}
        toggleAgent={toggleAgent}
        agentConfigLoading={agentConfigLoading}
        agentConfigSaving={agentConfigSaving}
        openAgentSettings={openAgentSettings}
        activeSubagents={activeSubagents}
        agentConfigError={agentConfigError}
        activeAgentDef={activeAgentDef}
        activeAgentConfig={activeAgentConfig}
        settingsBusy={settingsBusy}
        updateAgentDraft={updateAgentDraft}
        activeAgentSettings={activeAgentSettings}
        guardianRuleSummary={guardianRuleSummary}
        floatingAgentSettings={floatingAgentSettings}
        toggleFloatingAgentSettings={toggleFloatingAgentSettings}
        loadAgentConfig={loadAgentConfig}
        setAgentConfigError={setAgentConfigError}
        saveAgentSettings={saveAgentSettings}
        interactionBusy={interactionBusy}
        projectItems={projectItems}
        activeProjectKey={activeProjectKey}
        selectProject={selectProject}
        threadItems={threadItems}
        activeThread={activeThread}
        viewThread={viewThread}
      />
    </AppSidebarFrame>
  );
}
