export function createComposerViewModel({
  activeToken,
  activityDetail,
  paletteOpen,
  paletteRef,
  visiblePaletteItems,
  paletteWindowStart,
  paletteSelectedIndex,
  applyPaletteItem,
  collaborationMode,
  composerLocked,
  modeSwitchBusy,
  toggleComposerMode,
  focusComposer,
  inputRef,
  input,
  onInputChange,
  onInputFocus,
  onInputBlur,
  onInputSelect,
  onInputKeyDown,
  status,
  interrupt,
  sendMessage,
  isCompactWorkspaceLayout,
  isWorkspacePanelOpen,
  setIsWorkspacePanelOpen,
  startThread,
  interactionBusy,
  StopIcon,
  SendIcon,
  FolderIcon,
  NewChatIcon,
}) {
  return {
    activityDetail,
    paletteOpen,
    paletteRef,
    visiblePaletteItems,
    paletteWindowStart,
    paletteSelectedIndex,
    activeTokenType: activeToken?.type || "",
    onApplyPaletteItem: applyPaletteItem,
    collaborationMode,
    composerLocked,
    modeSwitchBusy,
    onToggleComposerMode: async () => {
      await toggleComposerMode();
      focusComposer();
    },
    inputRef,
    input,
    onInputChange,
    onInputFocus,
    onInputBlur,
    onInputSelect,
    onInputKeyDown,
    status,
    onInterrupt: interrupt,
    onSendMessage: sendMessage,
    isCompactWorkspaceLayout,
    isWorkspacePanelOpen,
    onToggleWorkspacePanel: () => setIsWorkspacePanelOpen((current) => !current),
    onNewChat: async () => startThread({ replaceCurrentTab: true }),
    interactionBusy,
    StopIcon,
    SendIcon,
    FolderIcon,
    NewChatIcon,
  };
}

export default function useComposerViewModel(options) {
  return createComposerViewModel(options);
}
