export type UseResizeInteractionsArgs = {
  sidebarMin: number;
  sidebarMax: number;
  workspacePanelMin: number;
  workspacePanelMax: number;
  workspacePreviewMinWidth: number;
  workspacePreviewMaxWidth: number;
  workspacePreviewMinHeight: number;
  workspacePreviewMaxHeight: number;
  workspacePreviewDefaultWidth: number;
  workspacePreviewDefaultHeight: number;
  isResizingSidebar: boolean;
  isResizingWorkspacePanel: boolean;
  isResizingWorkspacePreview: boolean;
  workspacePreview: unknown;
  isProjectModeModalOpen: boolean;
  shortcutModalPage: string;
  workspacePreviewWidth: number;
  workspacePreviewHeight: number;
  workspaceResizeRef: { current: { startX: number; startWidth: number } };
  workspacePreviewResizeRef: { current: { mode: string; startX: number; startY: number; startWidth: number; startHeight: number } };
  setSidebarWidth: (width: number) => void;
  setIsResizingSidebar: (next: boolean) => void;
  setWorkspacePanelWidth: (width: number) => void;
  setIsResizingWorkspacePanel: (next: boolean) => void;
  setWorkspacePreviewWidth: (width: number) => void;
  setWorkspacePreviewHeight: (height: number) => void;
  setIsResizingWorkspacePreview: (next: boolean) => void;
  setWorkspacePreview: (next: unknown) => void;
  persistWorkspacePreviewWidth: (width: number) => void;
  persistWorkspacePreviewHeight: (height: number) => void;
  clearWorkspacePreviewSize: () => void;
};
