export type ThreadSessionArgs = {
  api: (path: string, options?: Record<string, unknown>) => Promise<Record<string, unknown>>;
  me: Record<string, unknown> | null;
  activeProjectKey: string;
  activeProjectTabId: string;
  activeThread: string;
  isMobileLayout: boolean;
  interactionBusy: boolean;
  projectTabs: Array<Record<string, unknown>>;
  projectItems: Array<Record<string, unknown>>;
  threadItems: Array<Record<string, unknown>>;
  threadTabsByProjectTabId: Record<string, Array<Record<string, unknown>>>;
  activeThreadTabIdByProjectTabId: Record<string, string>;
  threadProjectTabIdByThreadId: Record<string, string>;
  initialLoadRef: { current: boolean };
  activeThreadRef: { current: string };
  pendingComposerFocusRef: { current: boolean };
  turnThreadIdRef: { current: Record<string, string> };
  setThreadItems: (items: Array<Record<string, unknown>>) => void;
  setProjectItems: (items: Array<Record<string, unknown>>) => void;
  setSessionSummary: (summary: Record<string, unknown>) => void;
  setProjectTabs: (updater: (prev: Array<Record<string, unknown>>) => Array<Record<string, unknown>>) => void;
  setThreadTabsByProjectTabId: (updater: (prev: Record<string, Array<Record<string, unknown>>>) => Record<string, Array<Record<string, unknown>>>) => void;
  setThreadProjectTabIdByThreadId: (updater: (prev: Record<string, string>) => Record<string, string>) => void;
  setActiveThreadTabIdByProjectTabId: (updater: (prev: Record<string, string>) => Record<string, string>) => void;
  setActiveProjectTabId: (tabId: string) => void;
  setActiveThread: (threadId: string) => void;
  setMessagesByThreadId: (updater: (prev: Record<string, Array<Record<string, unknown>>>) => Record<string, Array<Record<string, unknown>>>) => void;
  setMessages: (updater: Array<Record<string, unknown>> | ((prev: Array<Record<string, unknown>>) => Array<Record<string, unknown>>)) => void;
  setStatus: (next: string | ((current: string) => string)) => void;
  setStatusForThread: (threadId: string, next: string) => void;
  setStatusForActiveThread: (next: string) => void;
  setCollaborationMode: (mode: string) => void;
  setIsSidebarOpen: (open: boolean) => void;
  setPendingProjectTarget: (target: string) => void;
  setIsProjectModeModalOpen: (open: boolean) => void;
  appendMessageToThread: (threadId: string, message: Record<string, unknown>) => void;
  restoreThreadMessages: (threadId: string) => boolean;
  updateThreadUi: (threadId: string, patch: Record<string, unknown>) => void;
  syncThreadMessagesFromServerImpl?: (threadId: string, options?: { applyToVisible?: boolean }) => Promise<void>;
  upsertProjectTab: (project: Record<string, unknown>, options?: { forceNew?: boolean }) => string;
  openThreadInProjectTab: (projectTabId: string, thread: Record<string, unknown>) => string;
  setActiveThreadForProjectTab: (projectTabId: string, threadId: string) => void;
  updateThreadTabState: (threadId: string, patch: Record<string, unknown>) => void;
  ensureWorkspaceBucket: (threadId: string) => void;
  removeWorkspaceBucket: (threadId: string) => void;
  normalizeCollaborationMode: (raw: unknown) => "build" | "plan";
};
